//// Each #kernel tells which function to compile; you can have many kernels
//#pragma kernel CSMain

//// Create a RenderTexture with enableRandomWrite flag and set it
//// with cs.SetTexture
//RWTexture2D<float4> Result;

//[numthreads(8,8,1)]
//void CSMain (uint3 id : SV_DispatchThreadID)
//{
//    // TODO: insert actual code here!

//    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
//}

//#pragma kernel FillWithRed
//
//RWTexture2D<float4> texture;
//
//[numthreads(8, 8, 1)]
//void FillWithRed(uint3 dtid : SV_DispatchThreadID)
//{
//    texture[dtid.xy] = float4(1, 0, 0, 1);
//}