#pragma kernel ComposeColors

RWTexture2D<float4> _Source;
RWTexture2D<float4> _Destination;
uint2 _Resolution;

[numthreads(8,8,1)]
void ComposeColors (uint3 dtid : SV_DispatchThreadID)
{
    if (dtid.x < _Resolution.x & dtid.y < _Resolution.y)
    {
        // A OVER B Operation with premultiplied alpha
        // outcol = Acol + Bcol * (1 - Aalpha)
        // outalpha = Aalpha + Balpha * (1 - Aalpha)
        
        float4 col;
        col.rgb = _Source[dtid.xy].rgb + (_Destination[dtid.xy].rgb * (1 - _Source[dtid.xy].a));
        col.a = _Source[dtid.xy].a + _Destination[dtid.xy].a * (1 - _Source[dtid.xy].a);
        
        _Destination[dtid.xy] = col;
    }
}
