#pragma kernel Fill
#pragma kernel ComputeBinaryTexture

struct BinData
{
    uint data;
};

RWTexture2D<float4> _Texture;
RWStructuredBuffer<BinData> _BinTextureBuffer;
StructuredBuffer<BinData> _FillBuffer;
uint2 _Resolution;
uint2 _MinLimit;
uint2 _MaxLimit;
float4 _TargetColor;
float4 _FillColor;

[numthreads(8,8,1)]
void ComputeBinaryTexture(uint3 dtid : SV_DispatchThreadID)
{
    if (dtid.x >= _MinLimit.x && dtid.x <= _MaxLimit.x && dtid.y >= _MinLimit.y && dtid.y <= _MaxLimit.y)
    {
        // Due to float's precision difference in cpu and gpu, some colors didn't get fill because they were "different".
        // i.e: 0.09411765 from texture vs 0.09411766 from targetColor. To fix this, I clamp one decimal value from both color values.
        float4 textureColor = _Texture[dtid.xy];
        float4 targetColor = _TargetColor;
        
        textureColor = round(textureColor * 1000000) / 1000000;
        targetColor = round(targetColor * 1000000) / 1000000;
        
        if (textureColor.r == targetColor.r && textureColor.g == targetColor.g && textureColor.b == targetColor.b && textureColor.a == targetColor.a)
        {
            _BinTextureBuffer[dtid.y * _Resolution.x + dtid.x].data = 1;
            return;
        }
    }
    
    _BinTextureBuffer[dtid.y * _Resolution.x + dtid.x].data = 0;
}

[numthreads(8, 8, 1)]
void Fill(uint3 dtid : SV_DispatchThreadID)
{
    if (dtid.x < _Resolution.x && dtid.y < _Resolution.y)
    {
        if (_FillBuffer[_Resolution.x * dtid.y + dtid.x].data == 1)
        {
            _Texture[dtid.xy] = _FillColor.rgba;
        }
    }
}