#pragma kernel PlotSize

struct BrushData
{
    uint2 pos;
    uint2 size;
    float4 color;
};

RWTexture2D<float4> _Texture;
StructuredBuffer<BrushData> _Buffer;
uint2 _Resolution;

[numthreads(8, 8, 1)]
void PlotSize(uint3 dtid : SV_DispatchThreadID)
{
    if ((dtid.x < _Buffer[0].size.x && dtid.x < _Resolution.x) && (dtid.y < _Buffer[0].size.y && dtid.y < _Resolution.y))
    {
        uint2 index = _Buffer[0].pos.xy + dtid.xy - _Buffer[0].size.xy / 2;
        
        _Texture[index] = _Buffer[0].color;
    }
}